# config for cargo release (https://github.com/crate-ci/cargo-release)

pre-release-replacements = [
  {file="k8s/base/kustomization.yaml", search="newTag: .*", replace="newTag: {{version}}"},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/sg60/toggl-to-sheets/compare/{{tag_name}}...HEAD", exactly=1},
]
